### ISSUE TITLE
Open Issues for Godot4 4.0.1 Demos

### ISSUE THREAD

**Issue by GeorgeS2019** [GeorgeS2019/Godot4-3D-IK-Demo#1]
# Update 25th May 2023

## SkeletonIK3D

- [ ] [SkeletonIK3D bone roll axis is not working correctly](https://github.com/godotengine/godot/issues/77271)

<details>
<summary>Previous SkeletonIK3D discussions</summary>

[Source Link at Godot Demo](https://github.com/godotengine/godot-demo-projects/issues/697#issuecomment-1489363400)

# Update 31st March 2023

## List of WIP demo for IK and topics
- [ ] [Ballhead constraints for FABRIK](https://github.com/godotengine/godot/pull/62003)
   > @KaruroChori  => Do you have a screenshot to help us understand your IK PR?
- [ ] [IK and Physical Bone Improvements](https://github.com/godotengine/godot-proposals/issues/750)
  > @NHodgesVFX => Do you have a screenshot to help us understand your IK PR?
- [ ] [The ability to Limit(constraints) IK](https://github.com/godotengine/godot-proposals/issues/3712)
  > @ywmaa => Do you have a screenshot to help us understand your IK PR?
  > https://github.com/ywmaa/Advanced-Movement-System-Godot
- [ ] [New Animation Editor (with working mockup)
](https://github.com/godotengine/godot-proposals/issues/3950)
  > @rossunger => Do you have a screenshot to help us understand your IK PR?
- [ ] [Retool AnimationTree parameter system to use a blackboard-based approach](https://github.com/godotengine/godot-proposals/issues/3352)
- [ ] [Implement Motion Matching](https://github.com/godotengine/godot-proposals/issues/6122)
  > @Mikeysax => Do you have a screenshot to help us understand your IK PR?

</details>

<details>
<summary>Some of Open Issues for Godot4 4.0.1 Demos</summary>

# For Godot4 .NET 4.0.1
- [ ] 3d/add-physical-light-camera-units-demo => very timely new Godot4 demo
- [ ] 3d/[add-3d-sky-shaders-demo](https://github.com/godotengine/godot-demo-projects/pull/809) => **not working in godot 4**
<details>
<summary>Sky Shaders in Godot 4.0 | What You Should Know</summary>

https://www.youtube.com/watch?v=SzNmHPr4vf8
</details>

- [ ] 3d/add-large-world-coordinates-demo
- [ ] 3d/[ik](https://github.com/godotengine/godot-demo-projects/issues/853) => **no back-up plan and prompt decision/action**
<details>
<summary>Godot4 3D IK</summary>

## [discusison](https://github.com/godotengine/godot-proposals/issues/3099#issuecomment-1489596552)

Just found this=> 
## How should I introduce the current state of the ik problem?
https://docs.google.com/document/d/1SCG5FOuFqXti5RJIl5hVvU_h84JIpcedTw0AaAEycZs/edit#)

#### [Procedural Animation In Godot 4.0](https://www.youtube.com/watch?v=G_seJ2Yg1GA)
- https://github.com/CBerry22/Godot-4.0-Procedural-Animation
#### [Animation with Inverse Kinematics modifiers coming to Godot 4!](https://www.youtube.com/watch?v=6EkKXhTSBFY)
  - https://github.com/godotengine/godot-proposals/issues/3099#issuecomment-1489436457
- https://www.youtube.com/watch?v=w1RnhmC3hgI
- https://www.youtube.com/watch?v=_timNOvSm_U
- https://www.youtube.com/watch?v=H9wcD7X8pXM
</details>
- [ ] audio/generator

</details>

# User-Contributed Scenes
<details>
<summary>Godot 4.0.1</summary>

@RPicster
If you have sharable version, would be great

![image](https://user-images.githubusercontent.com/49812372/228676263-d2eafc92-ccbf-4596-a1d3-e02d2839eca7.png)

</details>
<details>
<summary>Godot 4.0.1 RC 2</summary>

https://github.com/godotengine/godot/issues/74965#issue-1626454140

![image](https://user-images.githubusercontent.com/49812372/228675635-e7d84e18-094e-411c-b691-031c6f638f72.png)

</details>
<details>
<summary>Godot 4.0.1 RC 1</summary>

https://github.com/perfoon/Abandoned-Spaceship-Godot-Demo
![image](https://user-images.githubusercontent.com/49812372/228675172-473d637a-dbe7-491d-9bcf-f29e0cbfb9fd.png)

</details>

<details>
<summary>Godot 4.0 RC 6</summary>

![image](https://user-images.githubusercontent.com/49812372/228676739-4a4490c6-55e1-4209-b7fe-bbfaec1fd71c.png)

</details>

<details>
<summary>Godot 4.0 RC 4</summary>

https://github.com/Calinou/godot-photo-mode-demo
![image](https://user-images.githubusercontent.com/49812372/228677342-8da3a529-c913-4c4f-aeae-fa1529619727.png)

</details>

<details>
<summary>Godot 4.0 beta 15</summary>

https://gitlab.com/magnusmj/godot4classroom
![image](https://user-images.githubusercontent.com/49812372/228677988-0dec42a1-98dc-4720-bdcc-9ac0adddce46.png)

</details>

<details>
<summary>Godot 4.0 beta 6</summary>

https://github.com/HungryProton/scatter/tree/v4

![image](https://user-images.githubusercontent.com/49812372/228679014-17c36078-41d7-42c2-a36b-5a88d7db17f8.png)

</details>

# Additions
<details>
<summary>Unreal Sun Temple Reference Scene</summary>

https://github.com/godotengine/godot/issues/75440

![image](https://user-images.githubusercontent.com/49812372/228682526-cd7e2a6f-1726-42f8-a0cb-85cbf876e9b1.png)

</details>
